#!/bin/bash

# SmokePing Quick Tunnel Creator
# Creates sessionless Cloudflare tunnels with autogenerated domains
# No Cloudflare account or token required!

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to detect running edition
detect_edition() {
    # Check for Basic edition
    if docker ps --format "{{.Names}}" | grep -q "smokeping-basic"; then
        echo "basic"
        return
    fi
    
    # Check for Standard edition
    if docker ps --format "{{.Names}}" | grep -q "smokeping-standard"; then
        echo "standard"
        return
    fi
    
    # Check for Pro edition (check for pro-specific containers or influxdb)
    if docker ps --format "{{.Names}}" | grep -qE "(^pro-|influxdb)"; then
        echo "pro"
        return
    fi
    
    # No edition detected
    echo "none"
}

# Function to check if tunnel is already running
is_tunnel_running() {
    local service_name=$1
    docker ps --format "{{.Names}}" | grep -q "tunnel-${service_name}" || return 1
}

# Function to wait for tunnel URL
wait_for_tunnel_url() {
    local container_name=$1
    local max_attempts=30
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        local url=$(docker logs "$container_name" 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || true)
        if [ -n "$url" ]; then
            echo "$url"
            return 0
        fi
        
        sleep 1
        ((attempt++))
    done
    
    return 1
}

# Function to start tunnel for a service
start_tunnel() {
    local service_name=$1
    local target_url=$2
    local description=$3
    local network=$4
    
    local container_name="tunnel-${service_name}"
    
    # Check if already running
    if is_tunnel_running "$service_name"; then
        echo -e "${YELLOW}⚠️  Tunnel for ${description} is already running${NC}"
        local existing_url=$(docker logs "$container_name" 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "URL not found")
        echo -e "   ${CYAN}→ ${existing_url}${NC}"
        return 0
    fi
    
    echo -e "${BLUE}🚇 Starting tunnel for ${description}...${NC}"
    
    # Start the tunnel container
    docker run -d \
        --name "$container_name" \
        --network "$network" \
        --restart unless-stopped \
        cloudflare/cloudflared:latest \
        tunnel --no-autoupdate --url "$target_url" \
        >/dev/null 2>&1
    
    # Wait for URL
    echo -n "   Waiting for tunnel URL..."
    if url=$(wait_for_tunnel_url "$container_name"); then
        echo -e "\r   ${GREEN}✅ ${description}: ${CYAN}${url}${NC}"
        return 0
    else
        echo -e "\r   ${RED}❌ Failed to get tunnel URL for ${description}${NC}"
        return 1
    fi
}

# Function to stop all tunnels
stop_all_tunnels() {
    echo -e "${YELLOW}🛑 Stopping all tunnels...${NC}"
    
    local tunnels=$(docker ps --format "{{.Names}}" | grep "^tunnel-" || true)
    if [ -z "$tunnels" ]; then
        echo -e "${CYAN}ℹ️  No tunnels are running${NC}"
        return
    fi
    
    for tunnel in $tunnels; do
        echo -e "   Stopping ${tunnel}..."
        docker stop "$tunnel" >/dev/null 2>&1
        docker rm "$tunnel" >/dev/null 2>&1
    done
    
    echo -e "${GREEN}✅ All tunnels stopped${NC}"
}

# Function to show all tunnel URLs
show_tunnel_urls() {
    local edition=$1
    
    echo -e "\n${PURPLE}🌐 Quick Tunnel URLs for SmokePing ${edition^} Edition${NC}"
    echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    
    # Get URLs from container logs
    case $edition in
        "basic")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            ;;
            
        "standard")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local webadmin_url=$(docker logs tunnel-webadmin 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            echo -e "${CYAN}Web Administration:${NC}  $webadmin_url"
            ;;
            
        "pro")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local webadmin_url=$(docker logs tunnel-webadmin 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local grafana_url=$(docker logs tunnel-grafana 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            echo -e "${CYAN}Web Administration:${NC}  $webadmin_url"
            echo -e "${CYAN}Grafana Dashboard:${NC}   $grafana_url"
            ;;
    esac
    
    echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "\n${YELLOW}⚠️  Note: These are temporary URLs that will change on restart${NC}"
    echo -e "${YELLOW}    For permanent URLs, use the token-based setup instead.${NC}"
}

# Function to create tunnels for specific edition
create_edition_tunnels() {
    local edition=$1
    
    echo -e "${GREEN}🚀 Creating Quick Tunnels for SmokePing ${edition^} Edition${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    
    case $edition in
        "basic")
            # Basic edition: Only SmokePing interface
            start_tunnel "smokeping" "http://smokeping-basic:80" "SmokePing Interface" "basic_smokeping-net"
            ;;
            
        "standard")
            # Standard edition: SmokePing + Web Admin
            # Note: Standard edition uses 'smokeping-net' network
            start_tunnel "smokeping" "http://smokeping-standard:80" "SmokePing Interface" "standard_smokeping-net"
            start_tunnel "webadmin" "http://smokeping-standard-web-admin:8080" "Web Administration" "standard_smokeping-net"
            ;;
            
        "pro")
            # Pro edition: SmokePing + Web Admin + Grafana
            # Pro edition uses default network for docker-compose
            start_tunnel "smokeping" "http://pro-smokeping-1:80" "SmokePing Interface" "pro_default"
            start_tunnel "webadmin" "http://pro-web-admin-1:8080" "Web Administration" "pro_default"
            start_tunnel "grafana" "http://pro-grafana-1:3000" "Grafana Dashboard" "pro_default"
            ;;
            
        *)
            echo -e "${RED}❌ Unknown edition: $edition${NC}"
            return 1
            ;;
    esac
    
    # Show all URLs
    show_tunnel_urls "$edition"
}

# Main function
main() {
    local action=${1:-create}
    
    case $action in
        "create"|"start")
            # Detect running edition
            local edition=$(detect_edition)
            
            if [ "$edition" == "none" ]; then
                echo -e "${RED}❌ No SmokePing edition is currently running!${NC}"
                echo -e "${YELLOW}Please start a SmokePing edition first:${NC}"
                echo -e "  cd editions/basic && ./setup.sh"
                echo -e "  cd editions/standard && docker-compose up -d"
                echo -e "  cd editions/pro && ./init-passwords.sh && docker-compose up -d"
                exit 1
            fi
            
            # Create tunnels for detected edition
            create_edition_tunnels "$edition"
            ;;
            
        "stop")
            stop_all_tunnels
            ;;
            
        "status"|"show")
            # Show current tunnel URLs
            local edition=$(detect_edition)
            if [ "$edition" == "none" ]; then
                echo -e "${RED}❌ No SmokePing edition is running${NC}"
                exit 1
            fi
            
            local tunnel_count=$(docker ps --format "{{.Names}}" | grep -c "^tunnel-")
            if [ "$tunnel_count" -eq 0 ]; then
                echo -e "${YELLOW}ℹ️  No tunnels are currently running${NC}"
                echo -e "Run '$0 create' to create tunnels"
                exit 0
            fi
            
            show_tunnel_urls "$edition"
            ;;
            
        "help"|"--help"|"-h")
            echo "SmokePing Quick Tunnel Creator"
            echo ""
            echo "Usage: $0 [command]"
            echo ""
            echo "Commands:"
            echo "  create, start  Create tunnels for running SmokePing edition (default)"
            echo "  stop           Stop all running tunnels"
            echo "  status, show   Show current tunnel URLs"
            echo "  help           Show this help message"
            echo ""
            echo "This tool creates temporary Cloudflare tunnels (*.trycloudflare.com)"
            echo "without requiring a Cloudflare account or domain."
            ;;
            
        *)
            echo -e "${RED}Unknown command: $action${NC}"
            echo "Use '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"