#!/bin/bash

# SmokePing Quick Tunnel Creator
# Creates sessionless Cloudflare tunnels with autogenerated domains
# No Cloudflare account or token required!

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# The running edition and its Compose project, from the labels Compose puts
# on every container -- never from guessed container names (Pro's are
# <project>-<service>-1, and the project name is whatever
# COMPOSE_PROJECT_NAME says). Sets EDITION_DIR, PROJECT and, for the
# ports, sources the edition's env file (relocatable: SMOKING_PI_ENV_FILE).
# Sets EDITION (not echoed: a $(...) call would lose the other variables).
detect_edition() {
    local dir
    for e in pro standard basic; do
        dir=$(docker ps --format '{{.Label "com.docker.compose.project.working_dir"}}' | grep "/editions/$e\$" | head -n1 || true)
        if [ -n "$dir" ]; then
            EDITION_DIR="$dir"
            PROJECT=$(docker ps --filter "label=com.docker.compose.project.working_dir=$dir" --format '{{.Label "com.docker.compose.project"}}' | head -n1)
            [ -n "$PROJECT" ] || { echo -e "${RED}❌ Containers under $dir carry no Compose project label; start the edition with docker compose or smoking-pi${NC}" >&2; exit 1; }
            local env_file="${SMOKING_PI_ENV_FILE:-$dir/.env}"
            # An if, not an && chain: a chain that fails at the source would
            # skip `set +a` and leave auto-export on for the rest of the run.
            if [ -r "$env_file" ]; then
                set -a
                # shellcheck disable=SC1090
                . "$env_file"
                set +a
            fi
            EDITION="$e"
            return
        fi
    done
    EDITION="none"
}

# Function to check if tunnel is already running
is_tunnel_running() {
    local service_name=$1
    docker ps --format "{{.Names}}" | grep -q "tunnel-${service_name}" || return 1
}

# Function to wait for tunnel URL
wait_for_tunnel_url() {
    local container_name=$1
    local max_attempts=30
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        local url=$(docker logs "$container_name" 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || true)
        if [ -n "$url" ]; then
            echo "$url"
            return 0
        fi
        
        sleep 1
        ((attempt++))
    done
    
    return 1
}

# Function to start tunnel for a service
start_tunnel() {
    local service_name=$1
    local target_url=$2
    local description=$3
    local network=$4
    
    local container_name="tunnel-${service_name}"
    
    # Check if already running
    if is_tunnel_running "$service_name"; then
        echo -e "${YELLOW}⚠️  Tunnel for ${description} is already running${NC}"
        local existing_url=$(docker logs "$container_name" 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "URL not found")
        echo -e "   ${CYAN}→ ${existing_url}${NC}"
        return 0
    fi
    
    echo -e "${BLUE}🚇 Starting tunnel for ${description}...${NC}"
    
    # Start the tunnel container
    # shellcheck disable=SC2086
    docker run -d \
        --name "$container_name" \
        --network "$network" ${TUNNEL_EXTRA_ARGS:-} \
        --restart unless-stopped \
        cloudflare/cloudflared:latest \
        tunnel --no-autoupdate --url "$target_url" \
        >/dev/null 2>&1
    
    # Wait for URL
    echo -n "   Waiting for tunnel URL..."
    if url=$(wait_for_tunnel_url "$container_name"); then
        echo -e "\r   ${GREEN}✅ ${description}: ${CYAN}${url}${NC}"
        return 0
    else
        echo -e "\r   ${RED}❌ Failed to get tunnel URL for ${description}${NC}"
        return 1
    fi
}

# Function to stop all tunnels
stop_all_tunnels() {
    echo -e "${YELLOW}🛑 Stopping all tunnels...${NC}"
    
    local tunnels=$(docker ps --format "{{.Names}}" | grep "^tunnel-" || true)
    if [ -z "$tunnels" ]; then
        echo -e "${CYAN}ℹ️  No tunnels are running${NC}"
        return
    fi
    
    for tunnel in $tunnels; do
        echo -e "   Stopping ${tunnel}..."
        docker stop "$tunnel" >/dev/null 2>&1
        docker rm "$tunnel" >/dev/null 2>&1
    done
    
    echo -e "${GREEN}✅ All tunnels stopped${NC}"
}

# Function to show all tunnel URLs
show_tunnel_urls() {
    local edition=$1
    
    echo -e "\n${PURPLE}🌐 Quick Tunnel URLs for SmokePing ${edition^} Edition${NC}"
    echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    
    # Get URLs from container logs
    case $edition in
        "basic")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            ;;
            
        "standard")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local webadmin_url=$(docker logs tunnel-webadmin 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            echo -e "${CYAN}Web Administration:${NC}  $webadmin_url"
            ;;
            
        "pro")
            local smokeping_url=$(docker logs tunnel-smokeping 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local webadmin_url=$(docker logs tunnel-webadmin 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            local grafana_url=$(docker logs tunnel-grafana 2>&1 | grep -o 'https://.*\.trycloudflare\.com' | head -1 || echo "Not available")
            echo -e "${CYAN}SmokePing Interface:${NC} $smokeping_url"
            echo -e "${CYAN}Web Administration:${NC}  $webadmin_url"
            echo -e "${CYAN}Grafana Dashboard:${NC}   $grafana_url"
            ;;
    esac
    
    echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "\n${YELLOW}⚠️  Note: These are temporary URLs that will change on restart${NC}"
    echo -e "${YELLOW}    For permanent URLs, use the token-based setup instead.${NC}"
}

# Function to create tunnels for specific edition
create_edition_tunnels() {
    local edition=$1
    
    echo -e "${GREEN}🚀 Creating Quick Tunnels for SmokePing ${edition^} Edition${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    
    # Targets are Compose SERVICE names on the edition's network: Compose
    # gives every service a DNS alias there, whatever the container is
    # called. Pro's SmokePing runs on the host network, so its tunnel joins
    # the bridge and reaches it through the host gateway on port 80.
    case $edition in
        "basic")
            start_tunnel "smokeping" "http://smokeping:80" "SmokePing Interface" "${PROJECT}_smokeping-net"
            ;;
            
        "standard")
            start_tunnel "smokeping" "http://smokeping:80" "SmokePing Interface" "${PROJECT}_smokeping-net"
            start_tunnel "webadmin" "http://web-admin:8080" "Web Administration" "${PROJECT}_smokeping-net"
            ;;
            
        "pro")
            TUNNEL_EXTRA_ARGS="--add-host host.docker.internal:host-gateway" \
                start_tunnel "smokeping" "http://host.docker.internal:80" "SmokePing Interface" "bridge"
            start_tunnel "webadmin" "http://web-admin:8080" "Web Administration" "${PROJECT}_default"
            start_tunnel "grafana" "http://grafana:3000" "Grafana Dashboard" "${PROJECT}_default"
            ;;
            
        *)
            echo -e "${RED}❌ Unknown edition: $edition${NC}"
            return 1
            ;;
    esac
    
    # Show all URLs
    show_tunnel_urls "$edition"
}

# Main function
main() {
    local action=${1:-create}
    
    case $action in
        "create"|"start")
            # Detect running edition
            detect_edition; local edition="$EDITION"
            
            if [ "$edition" == "none" ]; then
                echo -e "${RED}❌ No SmokePing edition is currently running!${NC}"
                echo -e "${YELLOW}Please start a SmokePing edition first:${NC}"
                echo -e "  cd editions/basic && ./setup.sh"
                echo -e "  cd editions/standard && ./setup.sh"
                echo -e "  cd editions/pro && ./setup.sh     (or: sudo smoking-pi install)"
                exit 1
            fi
            
            # Create tunnels for detected edition
            create_edition_tunnels "$edition"
            ;;
            
        "stop")
            stop_all_tunnels
            ;;
            
        "status"|"show")
            # Show current tunnel URLs
            detect_edition; local edition="$EDITION"
            if [ "$edition" == "none" ]; then
                echo -e "${RED}❌ No SmokePing edition is running${NC}"
                exit 1
            fi
            
            local tunnel_count=$(docker ps --format "{{.Names}}" | grep -c "^tunnel-")
            if [ "$tunnel_count" -eq 0 ]; then
                echo -e "${YELLOW}ℹ️  No tunnels are currently running${NC}"
                echo -e "Run '$0 create' to create tunnels"
                exit 0
            fi
            
            show_tunnel_urls "$edition"
            ;;
            
        "help"|"--help"|"-h")
            echo "SmokePing Quick Tunnel Creator"
            echo ""
            echo "Usage: $0 [command]"
            echo ""
            echo "Commands:"
            echo "  create, start  Create tunnels for running SmokePing edition (default)"
            echo "  stop           Stop all running tunnels"
            echo "  status, show   Show current tunnel URLs"
            echo "  help           Show this help message"
            echo ""
            echo "This tool creates temporary Cloudflare tunnels (*.trycloudflare.com)"
            echo "without requiring a Cloudflare account or domain."
            ;;
            
        *)
            echo -e "${RED}Unknown command: $action${NC}"
            echo "Use '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"