"""Is SmokePing actually measuring? Per-target freshness from RRD mtimes.

"Running" in /status means the SmokePing container is up. That says nothing
about whether a target added a minute ago was picked up, or whether one
stopped updating last Tuesday. SmokePing rewrites a target's RRD at every
step, so the file's modification time is the time of its last measurement.

The expected set is the generated Targets file (plus the CPE_Targets file
cpe_discovery.py writes and Targets @includes), not the RRDs on disk: the
reference Pi holds 180 RRDs for 30 targets, the rest left behind by targets
deleted long ago, and a count of files would report those as broken.

Everything here is pure, so it is tested without Docker; api.py supplies
the file contents and the mtimes it reads from the SmokePing container.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from typing import Dict, Iterable, List, Optional, Tuple

# SmokePing's own default, and the Database section's step on every edition.
DEFAULT_STEP = 300
# One missed step is a slow fping round, not a problem; two is.
GRACE_STEPS = 2
GRACE_SECONDS = 60

_SECTION = re.compile(r"^(\+{1,2})\s*(\S+)\s*$")
_KEY = re.compile(r"^(\w+)\s*=\s*(.*?)\s*$")


@dataclass(frozen=True)
class Expected:
    section: str
    name: str
    probe: str

    @property
    def rrd(self) -> str:
        """Path relative to SmokePing's datadir (/data in the container)."""
        return f"{self.section}/{self.name}.rrd"


@dataclass
class TargetFreshness:
    section: str
    name: str
    probe: str
    step: int
    age_seconds: Optional[int]
    state: str  # fresh | stale | pending | missing


def parse_targets(*texts: str) -> List[Expected]:
    """Two-level targets (``+ section`` / ``++ name``) with their probe.

    A target inherits ``probe`` from its section, which inherits it from
    the file's top level; that is SmokePing's rule. Deeper nesting is not
    generated by config-manager and is ignored.
    """
    out: List[Expected] = []
    for text in texts:
        top_probe = "FPing"
        section: Optional[str] = None
        section_probe: Optional[str] = None
        current: Optional[List[str]] = None  # [name, probe] of the open target
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("@") or line.startswith("*"):
                continue
            m = _SECTION.match(line)
            if m:
                if current is not None and section is not None:
                    out.append(Expected(section, current[0], current[1]))
                    current = None
                if len(m.group(1)) == 1:
                    section, section_probe = m.group(2), None
                elif section is not None:
                    current = [m.group(2), section_probe or top_probe]
                continue
            k = _KEY.match(line)
            if k and k.group(1) == "probe":
                if current is not None:
                    current[1] = k.group(2)
                elif section is not None:
                    section_probe = k.group(2)
                else:
                    top_probe = k.group(2)
        if current is not None and section is not None:
            out.append(Expected(section, current[0], current[1]))
    return out


def parse_probe_steps(probes_text: str, default: int = DEFAULT_STEP) -> Dict[str, int]:
    """``step`` per probe name; a ``++`` sub-probe inherits its parent's."""
    steps: Dict[str, int] = {}
    parent: Optional[str] = None
    current: Optional[str] = None
    for raw in probes_text.splitlines():
        line = raw.strip()
        m = _SECTION.match(line)
        if m:
            current = m.group(2)
            if len(m.group(1)) == 1:
                parent = current
                steps[current] = default
            else:
                steps[current] = steps.get(parent or "", default)
            continue
        k = _KEY.match(line)
        if k and k.group(1) == "step" and current is not None and k.group(2).isdigit():
            steps[current] = int(k.group(2))
    return steps


def parse_mtimes(find_output: str) -> Dict[str, float]:
    """``find /data -name '*.rrd' -printf '%T@ %P\\n'`` → {relative path: mtime}."""
    out: Dict[str, float] = {}
    for line in find_output.splitlines():
        stamp, _, path = line.partition(" ")
        try:
            out[path] = float(stamp)
        except ValueError:
            continue
    return out


def classify(
    expected: Iterable[Expected],
    steps: Dict[str, int],
    mtimes: Dict[str, float],
    now: float,
    targets_generated_at: Optional[float],
) -> Tuple[List[TargetFreshness], Dict[str, int]]:
    """Each expected target's state, and a count per state.

    * fresh   -- updated within GRACE_STEPS steps (+ a minute of slack)
    * stale   -- has data, but none for longer than that
    * pending -- no RRD yet, and the Targets file is younger than that:
                 a target added a moment ago, waiting for its first step
    * missing -- no RRD, and SmokePing has had time to write one
    """
    rows: List[TargetFreshness] = []
    counts = {"fresh": 0, "stale": 0, "pending": 0, "missing": 0}
    for e in expected:
        step = steps.get(e.probe, DEFAULT_STEP)
        limit = GRACE_STEPS * step + GRACE_SECONDS
        mtime = mtimes.get(e.rrd)
        if mtime is not None:
            age: Optional[int] = max(0, int(now - mtime))
            state = "fresh" if age <= limit else "stale"
        else:
            age = None
            young = targets_generated_at is not None and now - targets_generated_at <= limit
            state = "pending" if young else "missing"
        counts[state] += 1
        rows.append(TargetFreshness(e.section, e.name, e.probe, step, age, state))
    return rows, counts


def report(
    targets_text: str,
    cpe_text: str,
    probes_text: str,
    find_output: str,
    now: float,
    targets_generated_at: Optional[float],
) -> dict:
    """The JSON body of GET /measurements."""
    expected = parse_targets(targets_text, cpe_text)
    rows, counts = classify(
        expected, parse_probe_steps(probes_text), parse_mtimes(find_output),
        now, targets_generated_at,
    )
    # Worst first: what a person should look at is at the top.
    order = {"missing": 0, "stale": 1, "pending": 2, "fresh": 3}
    rows.sort(key=lambda r: (order[r.state], r.section, r.name))
    return {
        "measuring": counts["stale"] == 0 and counts["missing"] == 0,
        "counts": counts,
        "total": len(rows),
        "targets": [asdict(r) for r in rows],
    }
