active_targets:
  custom:
  - category: custom
    host: ns1.uba.ar
    name: UBA
    probe: FPing
    title: UBA
  - category: custom
    host: www.google.com
    name: Google6
    probe: FPing6
    title: Google6
  - name: UdeSA
    host: www.udesa.edu.ar
    title: UdeSA
    probe: FPing
    category: custom
  dns_resolvers:
  - category: dns_resolvers
    host: 8.8.8.8
    lookup: google.com
    name: GoogleDNS
    probe: DNS
    title: Google DNS
  - category: dns_resolvers
    host: 1.1.1.1
    lookup: cloudflare.com
    name: CloudflareDNS
    probe: DNS
    title: Cloudflare DNS
  - category: dns_resolvers
    host: 9.9.9.9
    lookup: quad9.net
    name: Quad9DNS
    probe: DNS
    title: Quad9 DNS
  netflix_oca:
  - host: 23.246.36.193
    metadata:
      asn: '2906'
      cache_id: c122
      city: Chicago
      domain: ipv4-c122-ord003-ix.1.oca.nflxvideo.net
      iata_code: ORD
      latitude: 41.87556
      location_code: ORD
      longitude: -87.62442
      raw_city: Chicago, IL
      type: real_oca
    name: Chicago_ORD_c122_1
    probe: FPing
    title: ipv4-c122-ord003-ix.1.oca.nflxvideo.net (Chicago ORD/c122_1)
  - host: 23.246.37.180
    metadata:
      asn: '2906'
      cache_id: c106
      city: Chicago
      domain: ipv4-c106-ord003-ix.1.oca.nflxvideo.net
      iata_code: ORD
      latitude: 41.87556
      location_code: ORD
      longitude: -87.62442
      raw_city: Chicago, IL
      type: real_oca
    name: Chicago_ORD_c106_2
    probe: FPing
    title: ipv4-c106-ord003-ix.1.oca.nflxvideo.net (Chicago ORD/c106_2)
  - host: 45.57.120.66
    metadata:
      asn: '2906'
      cache_id: c211
      city: Chicago
      domain: ipv4-c211-ord001-dev-ix.1.oca.nflxvideo.net
      iata_code: ORD
      latitude: 41.87556
      location_code: ORD
      longitude: -87.62442
      raw_city: Chicago, IL
      type: real_oca
    name: Chicago_ORD_c211_3
    probe: FPing
    title: ipv4-c211-ord001-dev-ix.1.oca.nflxvideo.net (Chicago ORD/c211_3)
  - host: 45.57.121.70
    metadata:
      asn: '2906'
      cache_id: c733
      city: Chicago
      domain: ipv4-c733-ord001-ix.1.oca.nflxvideo.net
      iata_code: ORD
      latitude: 41.87556
      location_code: ORD
      longitude: -87.62442
      raw_city: Chicago, IL
      type: real_oca
    name: Chicago_ORD_c733_4
    probe: FPing
    title: ipv4-c733-ord001-ix.1.oca.nflxvideo.net (Chicago ORD/c733_4)
  - host: 45.57.62.146
    metadata:
      asn: '2906'
      cache_id: c273
      city: Washington D.C.
      domain: ipv4-c273-was001-ix.1.oca.nflxvideo.net
      iata_code: WAS
      latitude: 38.89504
      location_code: WAS
      longitude: -77.036545
      raw_city: Washington D.C., DC
      type: real_oca
    name: Washington_DC_WAS_c273_5
    probe: FPing
    title: ipv4-c273-was001-ix.1.oca.nflxvideo.net (Washington D.C. WAS/c273_5)
  top_sites:
  - category: top_sites
    host: google.com
    name: google_com
    probe: FPing
    title: google.com
  - category: top_sites
    host: facebook.com
    name: facebook_com
    probe: FPing
    title: facebook.com
  - category: top_sites
    host: amazon.com
    name: amazon_com
    probe: FPing
    title: amazon.com
  - category: top_sites
    host: nytimes.com
    name: nytimes_com
    probe: FPing
    title: nytimes.com
  - category: top_sites
    host: apple.com
    name: apple_com
    probe: FPing
    title: apple.com
metadata:
  bandwidth_estimate_mbps: 0.0
  bootstrap_completed: true
  created_by: bootstrap
  last_updated: '2025-08-15T17:47:43.584942'
  total_targets: 16
  version: '1.0'
