version: '3.9'

services:
  smokeping:
    build: ./smokeping
    ports:
      - "8080:80"
    volumes:
      - smokeping-data:/var/lib/smokeping
    environment:
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      RRD_DIR: ${RRD_DIR}
    depends_on:
      - influxdb

  influxdb:
    build: ./influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_ORG: ${INFLUX_ORG}
      GF_LOG_LEVEL: debug
      GF_PROVISIONING_LOG_LEVEL: debug    # <─ add this line
    depends_on:
      - influxdb

volumes:
  smokeping-data:
  influxdb-data:
  grafana-data: