#!/usr/bin/env bash
# Build a Debian package of the tracked tree: code under /opt/smoking-pi,
# the CLI in /usr/bin, a systemd unit. No Docker needed to build; Docker is
# a runtime dependency of what it installs. Output: dist/smoking-pi_<ver>_all.deb
#
# This is the end-to-end trial from docs/packaging.md, not a supported
# install path yet: read that document for what still has to move out of
# the tree before a package can upgrade in place.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VERSION="${1:-$(sed -n 's/^version: *//p' "$ROOT/CITATION.cff")}"
STAGE="$(mktemp -d)"; trap 'rm -rf "$STAGE"' EXIT
PKG="$STAGE/smoking-pi"
mkdir -p "$PKG/DEBIAN" "$PKG/opt/smoking-pi" "$PKG/usr/bin" "$PKG/lib/systemd/system" "$PKG/etc/default"

# The committed tree at HEAD -- never the working tree: on the reference Pi
# the running stack rewrites editions/pro/config-manager/{config,output}, and
# a package built from the checkout would ship that deployment's target list.
( cd "$ROOT" && git archive --format=tar HEAD -- editions shared docs examples README.md LICENSE CHANGELOG.md CITATION.cff SECURITY.md ) \
    | tar -C "$PKG/opt/smoking-pi" -xf -
# Generated output is regenerated by config-manager on first start; ship the
# directory, not the reference Pi's last generation.
rm -f "$PKG/opt/smoking-pi/editions/"*/config-manager/output/Targets "$PKG/opt/smoking-pi/editions/"*/config-manager/output/Probes
install -m 0755 "$ROOT/packaging/smoking-pi" "$PKG/usr/bin/smoking-pi"
install -m 0644 "$ROOT/packaging/systemd/smoking-pi.service" "$PKG/lib/systemd/system/smoking-pi.service"
cat > "$PKG/etc/default/smoking-pi" <<'ENV'
# Overrides for the smoking-pi CLI and unit. Uncomment to change.
#SMOKING_PI_EDITION=pro
ENV
SIZE=$(du -sk "$PKG" | cut -f1)
cat > "$PKG/DEBIAN/control" <<CTL
Package: smoking-pi
Version: $VERSION
Section: net
Priority: optional
Architecture: all
Depends: docker.io | docker-ce, docker-compose-plugin | docker-compose-v2, openssl, python3, git
Recommends: whiptail, python3-yaml
Installed-Size: $SIZE
Maintainer: Esteban Carisimo <noreply@smoking-pi.dev>
Homepage: https://github.com/estcarisimo/smoking-pi
Description: SmokePing network monitoring for a Raspberry Pi, with Grafana, alerts and an MCP server
 A Docker Compose stack around SmokePing in three editions (Basic, Standard,
 Pro). This package installs the stack definition, the smoking-pi command
 and a systemd unit; images are built or pulled on first start.
CTL
cat > "$PKG/DEBIAN/postinst" <<'POST'
#!/bin/sh
set -e
if [ "$1" = configure ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
    echo "smoking-pi installed. Next: sudo smoking-pi install   (then: systemctl enable --now smoking-pi)"
fi
POST
cat > "$PKG/DEBIAN/prerm" <<'PRE'
#!/bin/sh
set -e
if [ "$1" = remove ]; then
    systemctl disable --now smoking-pi >/dev/null 2>&1 || true
fi
# Data stays: docker volumes and /opt/smoking-pi/editions/*/.env are not removed.
PRE
chmod 0755 "$PKG/DEBIAN/postinst" "$PKG/DEBIAN/prerm"
echo "/etc/default/smoking-pi" > "$PKG/DEBIAN/conffiles"

mkdir -p "$ROOT/dist"
OUT="$ROOT/dist/smoking-pi_${VERSION}_all.deb"
fakeroot dpkg-deb --build --root-owner-group "$PKG" "$OUT" >/dev/null
echo "$OUT"
