"""Is SmokePing measuring? freshness.py, the reload that must tell the truth,
and GET /measurements against a fake Docker client."""

from types import SimpleNamespace

import pytest

import api as api_module
import freshness

TARGETS = """*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher

+ websites
menu = Websites
title = Websites

++ Google
menu = Google
host = google.com

++ NYT
host = nytimes.com

+ DNS_Resolvers
menu = DNS
title = DNS

++ GoogleDNS
probe = DNS
host = 8.8.8.8

+ HTTP
probe = CurlHTTP2

++ Example
host = example.com

# CPE targets (auto-discovered by cpe_discovery.py)
@include /config/CPE_Targets
"""

CPE = """# Auto-generated by cpe_discovery.py — do not edit
+ CPE
menu = CPE
title = ISP CPE Monitoring (auto-discovered)

++ CPE_IPv4
host = 136.25.220.1
"""

PROBES = """*** Probes ***

+ FPing
binary = /usr/sbin/fping
step = 300
pings = 10

+ DNS
binary = /usr/bin/dig
step = 60

+ Curl
step = 120

++ CurlHTTP1
pings = 5

++ CurlHTTP2
step = 600
"""

NOW = 1_800_000_000.0


def test_parse_targets_inherits_probe_from_file_then_section():
    got = {(e.section, e.name): e.probe for e in freshness.parse_targets(TARGETS, CPE)}
    assert got == {
        ("websites", "Google"): "FPing",
        ("websites", "NYT"): "FPing",
        ("DNS_Resolvers", "GoogleDNS"): "DNS",
        ("HTTP", "Example"): "CurlHTTP2",
        ("CPE", "CPE_IPv4"): "FPing",
    }


def test_rrd_path_is_section_slash_name():
    e = freshness.Expected("websites", "Google", "FPing")
    assert e.rrd == "websites/Google.rrd"


def test_parse_probe_steps_sub_probe_inherits_parent_unless_set():
    steps = freshness.parse_probe_steps(PROBES)
    assert steps["FPing"] == 300
    assert steps["DNS"] == 60
    assert steps["CurlHTTP1"] == 120  # inherited from + Curl
    assert steps["CurlHTTP2"] == 600  # its own


def test_parse_mtimes_skips_garbage():
    got = freshness.parse_mtimes("1790116077.2396 websites/Google.rrd\nnot-a-number x.rrd\n\n")
    assert got == {"websites/Google.rrd": 1790116077.2396}


def _find(**ages):
    return "".join(f"{NOW - age} {path}\n" for path, age in ages.items())


def test_classify_fresh_stale_pending_missing():
    expected = freshness.parse_targets(TARGETS, CPE)
    steps = freshness.parse_probe_steps(PROBES)
    mtimes = freshness.parse_mtimes(_find(**{
        "websites/Google.rrd": 290,         # within one step
        "websites/NYT.rrd": 2 * 300 + 61,   # past two steps + slack
        "DNS_Resolvers/GoogleDNS.rrd": 170,  # DNS step is 60: 2*60+60=180
        "CPE/CPE_IPv4.rrd": 10,
    }))
    # Example was added 30 s ago; everything else long ago.
    rows, counts = freshness.classify(expected, steps, mtimes, NOW,
                                      changed_at={"Example": NOW - 30})
    state = {r.name: r.state for r in rows}
    assert state == {"Google": "fresh", "NYT": "stale", "GoogleDNS": "fresh",
                     "Example": "pending", "CPE_IPv4": "fresh"}
    assert counts == {"fresh": 3, "stale": 1, "pending": 1, "missing": 0}

    # The same absent RRD, long after the target was added: missing.
    rows, counts = freshness.classify(expected, steps, mtimes, NOW,
                                      changed_at={"Example": NOW - 3 * 600})
    assert {r.name: r.state for r in rows}["Example"] == "missing"


def test_an_unrelated_regeneration_does_not_make_a_broken_target_pending():
    # The review of #104: "pending" was keyed to the Targets file's mtime,
    # which every regeneration bumps -- another target's edit, the IPv6
    # recheck -- so a target with no data for weeks read as "just added"
    # for ten minutes after each. Only its own change, or SmokePing's start,
    # counts now; another target changing a moment ago does not.
    expected = freshness.parse_targets(TARGETS, CPE)
    rows, _ = freshness.classify(
        expected, freshness.parse_probe_steps(PROBES), {}, NOW,
        changed_at={"Google": NOW - 10, "Example": NOW - 30 * 86400},
        started_at=NOW - 30 * 86400)
    state = {r.name: r.state for r in rows}
    assert state["Example"] == "missing"
    assert state["Google"] == "pending"


def test_a_re_enabled_target_waits_for_new_data_rather_than_reading_stale():
    # Its RRD is from before it was switched off; it changed 20 s ago.
    rows, _ = freshness.classify(
        [freshness.Expected("websites", "NYT", "FPing")], {"FPing": 300},
        {"websites/NYT.rrd": NOW - 5 * 86400}, NOW,
        changed_at={"NYT": NOW - 20})
    assert rows[0].state == "pending"
    assert rows[0].age_seconds == 5 * 86400


def test_right_after_smokeping_starts_nothing_is_missing_yet():
    # A fresh install, and the router target, which has no database row.
    expected = freshness.parse_targets(TARGETS, CPE)
    rows, counts = freshness.classify(
        expected, freshness.parse_probe_steps(PROBES), {}, NOW,
        started_at=NOW - 60)
    assert counts["missing"] == 0
    assert {r.name: r.state for r in rows}["CPE_IPv4"] == "pending"


def test_fresh_data_wins_over_a_recent_change():
    rows, _ = freshness.classify(
        [freshness.Expected("websites", "Google", "FPing")], {"FPing": 300},
        {"websites/Google.rrd": NOW - 5}, NOW,
        changed_at={"Google": NOW - 60}, started_at=NOW - 30)
    assert rows[0].state == "fresh"


def test_orphan_rrds_of_deleted_targets_are_not_reported():
    # The reference Pi: 180 RRDs on disk for 30 targets.
    body = freshness.report(TARGETS, CPE, PROBES,
                            _find(**{"websites/Google.rrd": 1, "old/Gone.rrd": 1}),
                            NOW)
    names = {t["name"] for t in body["targets"]}
    assert "Gone" not in names
    assert body["total"] == 5


def test_report_worst_first_and_measuring_flag():
    body = freshness.report(TARGETS, CPE, PROBES,
                            _find(**{"websites/Google.rrd": 1, "websites/NYT.rrd": 5000,
                                     "DNS_Resolvers/GoogleDNS.rrd": 1,
                                     "HTTP/Example.rrd": 1, "CPE/CPE_IPv4.rrd": 1}),
                            NOW)
    assert body["measuring"] is False
    assert body["targets"][0]["name"] == "NYT"
    assert body["targets"][0]["state"] == "stale"
    # Pending alone does not make it "not measuring": a target just added.
    body = freshness.report(TARGETS, CPE, PROBES,
                            _find(**{"websites/Google.rrd": 1, "websites/NYT.rrd": 1,
                                     "DNS_Resolvers/GoogleDNS.rrd": 1,
                                     "CPE/CPE_IPv4.rrd": 1}),
                            NOW, changed_at={"Example": NOW - 30})
    assert body["counts"]["pending"] == 1
    assert body["measuring"] is True


# --- the Docker side --------------------------------------------------------

class FakeContainer:
    def __init__(self, replies):
        self.replies = replies  # {argv[0]: (exit_code, bytes)}
        self.calls = []

    def exec_run(self, cmd):
        self.calls.append(cmd)
        code, out = self.replies.get(cmd[0], (0, b""))
        return SimpleNamespace(exit_code=code, output=out)


@pytest.fixture()
def fake_docker(monkeypatch):
    def install(replies):
        container = FakeContainer(replies)
        client = SimpleNamespace(containers=SimpleNamespace(get=lambda name: container))
        monkeypatch.setattr(api_module.docker, "from_env", lambda: client)
        monkeypatch.setattr(api_module, "resolve_container_name", lambda svc: "pro-smokeping-1")
        return container
    return install


def test_reload_reports_success_only_when_killall_signalled(fake_docker):
    fake_docker({"killall": (0, b"")})
    assert api_module.api._signal_smokeping_reload() is True


def test_reload_reports_failure_when_killall_found_no_process(fake_docker):
    # killall's exit code on the live container when nothing matched: 1.
    fake_docker({"killall": (1, b"killall: smokeping: no process killed")})
    assert api_module.api._signal_smokeping_reload() is False


def test_reload_reports_failure_when_docker_unreachable(monkeypatch):
    def boom():
        raise RuntimeError("no docker socket")
    monkeypatch.setattr(api_module.docker, "from_env", boom)
    monkeypatch.setattr(api_module, "resolve_container_name", lambda svc: "x")
    assert api_module.api._signal_smokeping_reload() is False


def test_generate_says_when_the_reload_was_not_confirmed(fake_docker, monkeypatch):
    fake_docker({"killall": (1, b"")})
    monkeypatch.setattr(api_module.api.generator, "run", lambda: True)
    body = api_module.api.generate_smokeping_config()
    assert body["success"] is True
    assert body["reloaded"] is False
    assert "did not confirm" in body["message"]


@pytest.fixture()
def client(monkeypatch):
    monkeypatch.delenv("CONFIG_API_TOKEN", raising=False)
    api_module.app.config["TESTING"] = True
    with api_module.app.test_client() as c:
        yield c


def test_measurements_endpoint(client, fake_docker, monkeypatch, tmp_path):
    (tmp_path / "Targets").write_text(TARGETS)
    (tmp_path / "Probes").write_text(PROBES)
    monkeypatch.setattr(api_module, "OUTPUT_DIR", tmp_path)
    monkeypatch.setattr(api_module.time, "time", lambda: NOW)
    container = fake_docker({
        "find": (0, _find(**{"websites/Google.rrd": 5}).encode()),
        "cat": (0, CPE.encode()),
    })
    monkeypatch.setattr(api_module.api, "_target_change_ages", lambda: {"NYT": 20.0})
    body = client.get("/measurements").get_json()
    assert body["available"] is True
    # The per-target change age from PostgreSQL reached the classifier.
    assert {t["name"]: t["state"] for t in body["targets"]}["NYT"] == "pending"
    assert body["total"] == 5
    assert body["counts"]["fresh"] == 1
    # It read the CPE file from inside the SmokePing container, and listed
    # RRDs with one line per file.
    assert ["cat", "/config/CPE_Targets"] in container.calls
    find_cmd = next(c for c in container.calls if c[0] == "find")
    assert find_cmd[-1] == "%T@ %P\\n"


def test_container_started_at_parses_docker_nanoseconds():
    c = SimpleNamespace(attrs={"State": {"StartedAt": "2026-09-22T01:10:05.486419656Z"}})
    assert api_module._container_started_at(c) == pytest.approx(1790039405.486419)
    never = SimpleNamespace(attrs={"State": {"StartedAt": "0001-01-01T00:00:00Z"}})
    assert api_module._container_started_at(never) is None
    assert api_module._container_started_at(SimpleNamespace()) is None


def test_measurements_without_generated_targets(client, monkeypatch, tmp_path):
    monkeypatch.setattr(api_module, "OUTPUT_DIR", tmp_path)
    body = client.get("/measurements").get_json()
    assert body == {"available": False, "reason": "no generated Targets file yet"}


def test_measurements_requires_the_token(client, monkeypatch):
    monkeypatch.setenv("CONFIG_API_TOKEN", "sekrit")
    assert client.get("/measurements").status_code == 401
