#!/bin/bash
# Password initialization script for SmokePing stack
# Run this script BEFORE starting docker-compose

set -e

ENV_FILE="./.env"
ENV_TEMPLATE="./.env.template"
ENV_BACKUP="./.env.backup"

# Function to generate secure random string
generate_password() {
    length=${1:-32}
    # Use URL-safe base64 to avoid problematic characters (/, +)
    # Replace / with _ and + with - for URL/path safety
    openssl rand -base64 $length | tr -d '=' | tr '/' '_' | tr '+' '-'
}

# Function to detect timezone
detect_timezone() {
    # Try multiple methods to detect timezone
    if [ -f /etc/timezone ]; then
        cat /etc/timezone | tr -d '\n'
    elif [ -f /etc/localtime ]; then
        # Try to find matching timezone file
        find /usr/share/zoneinfo -type f -exec cmp -s /etc/localtime {} \; -print | \
            head -n1 | sed 's|/usr/share/zoneinfo/||' || echo "UTC"
    else
        echo "UTC"
    fi
}

echo "🚀 SmokePing Stack - Zero-Touch Password Initialization"
echo "======================================================"

# Check if .env exists and has non-default values
if [ -f "$ENV_FILE" ]; then
    echo "📄 Found existing .env file, checking for defaults..."
    
    # Check if passwords are still defaults
    if grep -q "supersecrettoken" "$ENV_FILE" || \
       grep -q "your-secret-key-here" "$ENV_FILE" || \
       grep -q "DOCKER_INFLUXDB_INIT_PASSWORD" "$ENV_FILE" | grep -qv "=" || \
       grep -q "POSTGRES_PASSWORD" "$ENV_FILE" | grep -qv "=" ; then
        echo "⚠️  Default values detected, regenerating passwords..."
        # Backup existing file
        cp "$ENV_FILE" "$ENV_BACKUP.$(date +%s)"
        need_generation=true
    else
        echo "✅ Valid passwords found, skipping generation"
        exit 0
    fi
else
    echo "📝 No .env file found, creating new configuration..."
    need_generation=true
fi

if [ "$need_generation" = "true" ]; then
    # Generate passwords
    echo "🔐 Generating secure random passwords..."
    INFLUX_PASSWORD=$(generate_password 32)
    INFLUX_TOKEN=$(generate_password 32)
    SECRET_KEY=$(generate_password 48)
    POSTGRES_PASSWORD=$(generate_password 32)
    WEB_ADMIN_PASSWORD=$(generate_password 32)
    GRAFANA_ADMIN_PASSWORD=$(generate_password 32)
    GRAFANA_SECRET_KEY=$(generate_password 48)
    
    # Detect timezone
    echo "🌍 Detecting system timezone..."
    DETECTED_TZ=$(detect_timezone)
    echo "   Detected: $DETECTED_TZ"
    
    # Create new .env file
    cat > "$ENV_FILE" << EOF
# .env - Auto-generated by zero-touch deployment
# Generated: $(date)
# -------------------------------------------------------------------
# SmokePing + InfluxDB + Grafana stack
# -------------------------------------------------------------------

# InfluxDB connection
INFLUX_URL=http://influxdb:8086
INFLUX_TOKEN=${INFLUX_TOKEN}
INFLUX_ORG=smokingpi
INFLUX_BUCKET=latency

# InfluxDB admin credentials
DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}

# PostgreSQL credentials
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# SmokePing RRD directory inside its container
RRD_DIR=/var/lib/smokeping

# Timezone configuration (auto-detected: ${DETECTED_TZ})
TZ=${DETECTED_TZ}

# Web Admin Interface
SECRET_KEY=${SECRET_KEY}
WEB_ADMIN_USERNAME=admin
WEB_ADMIN_PASSWORD=${WEB_ADMIN_PASSWORD}

# Grafana admin credentials
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}

# -------------------------------------------------------------------
# IMPORTANT: This file contains sensitive information.
# Do not commit to version control!
# Run ./show-passwords.sh to display all credentials
# -------------------------------------------------------------------
EOF

    # Set secure permissions
    chmod 600 "$ENV_FILE"
    
    echo "✅ Password generation complete!"
    echo ""
    echo "📋 Generated Credentials:"
    echo "   InfluxDB Password: ${INFLUX_PASSWORD:0:8}..."
    echo "   InfluxDB Token: ${INFLUX_TOKEN:0:8}..."
    echo "   PostgreSQL Password: ${POSTGRES_PASSWORD:0:8}..."
    echo "   Web Admin Password: ${WEB_ADMIN_PASSWORD:0:8}..."
    echo "   Grafana Password: ${GRAFANA_ADMIN_PASSWORD:0:8}..."
    echo "   Grafana Secret Key: ${GRAFANA_SECRET_KEY:0:8}..."
    echo "   Web Admin Secret Key: ${SECRET_KEY:0:8}..."
    echo ""
    echo "💡 Run ./show-passwords.sh to see full credentials"
    echo ""
    
    # Also create a one-time display file for immediate viewing
    cat > "./.passwords-generated" << EOF
🎉 Zero-Touch Deployment Complete!
=================================

Generated on: $(date)
Timezone: ${DETECTED_TZ}

InfluxDB Admin Password: ${INFLUX_PASSWORD}
InfluxDB API Token: ${INFLUX_TOKEN}
PostgreSQL Password: ${POSTGRES_PASSWORD}
Web Admin Username: admin
Web Admin Password: ${WEB_ADMIN_PASSWORD}
Web Admin Secret Key: ${SECRET_KEY}
Grafana Admin Username: admin
Grafana Admin Password: ${GRAFANA_ADMIN_PASSWORD}
Grafana Secret Key: ${GRAFANA_SECRET_KEY}

Save these credentials securely!
This file will be deleted after first viewing.
EOF
    
    chmod 600 "./.passwords-generated"
fi

# Check for existing volumes and warn if they exist
echo "🔍 Checking for existing data volumes..."

GRAFANA_VOLUME_EXISTS=false
INFLUXDB_VOLUME_EXISTS=false
POSTGRES_VOLUME_EXISTS=false

if docker volume ls | grep -q "grafana-influx_grafana-data"; then
    GRAFANA_VOLUME_EXISTS=true
fi

if docker volume ls | grep -q "grafana-influx_influxdb-data"; then
    INFLUXDB_VOLUME_EXISTS=true
fi

if docker volume ls | grep -q "grafana-influx_postgres-data"; then
    POSTGRES_VOLUME_EXISTS=true
fi

if [ "$GRAFANA_VOLUME_EXISTS" = "true" ] || [ "$INFLUXDB_VOLUME_EXISTS" = "true" ] || [ "$POSTGRES_VOLUME_EXISTS" = "true" ]; then
    echo ""
    echo "⚠️  EXISTING VOLUMES DETECTED!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    if [ "$GRAFANA_VOLUME_EXISTS" = "true" ]; then
        echo "   📊 Grafana volume found - admin password will be reset automatically"
    fi
    
    if [ "$INFLUXDB_VOLUME_EXISTS" = "true" ]; then
        echo "   🗄️  InfluxDB volume found - THIS WILL CAUSE AUTHORIZATION ERRORS!"
        echo ""
        echo "   🚨 CRITICAL: InfluxDB has existing data with different tokens."
        echo "      Grafana dashboards will show 'unauthorized access' errors."
        echo ""
        echo "   🛠️  TO FIX: Reset InfluxDB volume with these commands:"
        echo "      docker-compose down"
        echo "      docker volume rm grafana-influx_influxdb-data"
        echo "      docker-compose up -d"
        echo ""
        echo "   ⚡ This will reset InfluxDB to use the current generated tokens."
        echo "      SmokePing will repopulate data automatically."
    fi
    
    if [ "$POSTGRES_VOLUME_EXISTS" = "true" ]; then
        echo "   🐘 PostgreSQL volume found - THIS WILL CAUSE DATABASE CONNECTION ERRORS!"
        echo ""
        echo "   🚨 CRITICAL: PostgreSQL has existing users with different passwords."
        echo "      Config-manager will fail to connect and fall back to YAML mode."
        echo "      Grafana template variables will show 'error executing SQL query'."
        echo ""
        echo "   🛠️  TO FIX: Reset PostgreSQL volume with these commands:"
        echo "      docker-compose down"
        echo "      docker volume rm grafana-influx_postgres-data"
        echo "      docker-compose up -d"
        echo ""
        echo "   ⚡ This will reset PostgreSQL to use the current generated password."
        echo "      Database will be populated automatically from YAML files."
    fi
    
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
fi

echo "✅ Initialization complete!"