# shellcheck shell=bash
# smoking-pi config: `config`, env-file settings by name.
# Sourced by cli/smoking-pi, never run on its own.

template_file() { echo "$EDITION_DIR/.env.template"; }

# Keys the edition's template declares, in its order. Only these can be set:
# a typo would otherwise be written, read by nothing, and look applied.
template_keys() { sed -n 's/^\([A-Z][A-Z0-9_]*\)=.*/\1/p' "$(template_file)" | awk '!seen[$0]++'; }

is_secret_key() {
    case "$1" in
        # A webhook URL is often the credential itself (Slack, Discord, ntfy).
        *TOKEN*|*PASSWORD*|*SECRET*|*_KEY|ALERT_WEBHOOK_URL) return 0 ;;
    esac
    return 1
}

# Generated by setup.sh at install, or fixed by it: the data volumes hold
# them (the PostgreSQL role's password, InfluxDB's token, Grafana's stored
# admin), so changing the env file alone breaks the service it feeds.
# Same reason `install` refuses to run over an existing env file.
is_install_key() {
    case "$1" in
        *_PORT) return 1 ;;  # a port mapping, not a credential
        POSTGRES_*|INFLUX_*|DOCKER_INFLUXDB_*|CLICKHOUSE_*|GF_SECURITY_*|\
        WEB_ADMIN_PASSWORD|SECRET_KEY|CONFIG_API_TOKEN|MCP_API_TOKEN|TSDB_TYPE) return 0 ;;
    esac
    return 1
}

# The compose services whose definition mentions ${KEY...}: the ones to
# recreate after it changes. COMPOSE_PROFILES decides which services exist
# at all, so it applies to the whole stack.
services_reading() {
    local key="$1" f
    for f in "$EDITION_DIR"/docker-compose*.yml; do
        [ -f "$f" ] || continue
        awk -v key="$key" '
            /^services:/ { in_services = 1; next }
            /^[^ #]/ { in_services = 0 }
            in_services && /^  [A-Za-z0-9_.-]+:[ ]*$/ { svc = $1; sub(":", "", svc); next }
            in_services && svc != "" && (match($0, "[$][{]" key "[:}?-]") || match($0, "[$]" key "([^A-Za-z0-9_]|$)")) { print svc }
        ' "$f"
    done | sort -u
}

closest_key() {
    # The declared key that shares the longest prefix with a typo.
    local want="$1" best="" best_len=0 k n
    while read -r k; do
        n=0
        while [ "$n" -lt "${#k}" ] && [ "${k:0:$((n + 1))}" = "${want:0:$((n + 1))}" ]; do
            n=$((n + 1))
        done
        if [ "$n" -gt "$best_len" ]; then best="$k"; best_len="$n"; fi
    done < <(template_keys)
    [ "$best_len" -ge 3 ] && echo "$best"
}

check_known_key() {
    local key="$1" hint
    # Not `template_keys | grep -q`: under pipefail, grep closing the pipe
    # early can fail the writer and make a declared key look unknown.
    if ! grep -qx "$key" <(template_keys); then
        echo "$key is not a setting of the $SMOKING_PI_EDITION edition (.env.template does not declare it)." >&2
        hint="$(closest_key "$key")"
        [ -z "$hint" ] || echo "Did you mean $hint?" >&2
        return 2
    fi
}

config_apply() {
    local key="$1" services
    if [ "$key" = COMPOSE_PROFILES ]; then
        echo "Applying: the profiles decide which services run, so the whole stack."
        compose up -d --remove-orphans
        remove_disabled
        return
    fi
    # Only services the recorded profiles enable: naming a service on
    # `compose up` starts it even when its profile is off, and setting an
    # alerter key must not quietly start an alerter nobody enabled.
    local enabled
    if ! enabled="$(compose config --services 2>/dev/null)"; then
        echo "Written, but Compose could not read the stack ('smoking-pi up' shows why); nothing recreated." >&2
        return 1
    fi
    services="$(services_reading "$key" | { grep -Fxf <(printf '%s\n' "$enabled") || true; } | tr '\n' ' ')"
    if [ -z "${services// /}" ]; then
        if [ -n "$(services_reading "$key")" ]; then
            echo "$key is read by $(services_reading "$key" | tr '\n' ' ')which no enabled profile runs; it applies once one does."
        else
            echo "No service of this edition reads $key; nothing to recreate."
        fi
        return
    fi
    echo "Applying: recreating ${services% }"
    # shellcheck disable=SC2086  # one word per service
    compose up -d $services
}

cmd_config() {
    need_edition
    [ -f "$(template_file)" ] || { echo "no $(template_file) here" >&2; return 1; }
    local sub="${1:-list}"; shift || true
    case "$sub" in
        list)
            local k v
            while read -r k; do
                v="$(env_get "$k")"
                if [ -z "$v" ]; then
                    printf '%-34s (unset: the default applies)\n' "$k"
                elif is_secret_key "$k"; then
                    printf '%-34s (set, hidden)\n' "$k"
                else
                    printf '%-34s %s\n' "$k" "$v"
                fi
            done < <(template_keys)
            ;;
        get)
            local key="${1:-}" show=0
            [ -n "$key" ] || { echo "usage: smoking-pi config get KEY [--show-secrets]" >&2; return 2; }
            [ "${2:-}" = --show-secrets ] && show=1
            check_known_key "$key" || return 2
            if is_secret_key "$key" && [ "$show" = 0 ]; then
                if [ -n "$(env_get "$key")" ]; then echo "(set, hidden: --show-secrets prints it)"; else echo "(unset)"; fi
                return 0
            fi
            local got
            got="$(env_get "$key")"
            if [ -n "$got" ]; then echo "$got"; else echo "(unset: the default applies)"; fi
            ;;
        set|unset)
            local key="${1:-}" value="" apply=1 arg
            [ -n "$key" ] || { echo "usage: smoking-pi config set KEY [VALUE] [--no-apply] | unset KEY [--no-apply]" >&2; return 2; }
            shift
            local have_value=0
            for arg in "$@"; do
                case "$arg" in
                    --no-apply) apply=0 ;;
                    *)
                        [ "$have_value" = 0 ] || { echo "one value only (quote it if it has spaces)" >&2; return 2; }
                        value="$arg"; have_value=1 ;;
                esac
            done
            check_known_key "$key" || return 2
            if is_install_key "$key"; then
                echo "$key was generated or fixed at install, and the data volumes hold it:" >&2
                echo "changing it in the env file alone would lock the service it feeds out." >&2
                case "$key" in
                    MCP_API_TOKEN) echo "'smoking-pi openclaw' manages the MCP token." >&2 ;;
                    TSDB_TYPE) echo "Switching backends is a reinstall; see docs/clickhouse.md." >&2 ;;
                esac
                return 2
            fi
            if [ "$sub" = unset ]; then
                value=""
            elif is_secret_key "$key"; then
                if [ "$have_value" = 1 ]; then
                    echo "$key is a secret: it is not taken from the command line, where" >&2
                    echo "ps and the shell history would keep it. Leave VALUE out and type it," >&2
                    echo "or pipe it: printf %s \"\$VALUE\" | smoking-pi config set $key" >&2
                    return 2
                fi
                if [ -t 0 ]; then
                    read -r -s -p "$key: " value; echo
                else
                    IFS= read -r value || true
                fi
                [ -n "$value" ] || { echo "nothing read for $key; to clear it: smoking-pi config unset $key" >&2; return 2; }
            elif [ "$have_value" = 0 ]; then
                echo "usage: smoking-pi config set $key VALUE" >&2
                return 2
            fi
            case "$value" in
                *$'\n'*|*$'\r'*) echo "a value cannot span lines" >&2; return 2 ;;
                *"'"*) echo "a value cannot contain ' : neither Compose nor the shell reading the env file could keep it" >&2; return 2 ;;
            esac
            if [ "$(env_get "$key")" = "$value" ]; then
                echo "$key is already that; nothing changed."
                return 0
            fi
            env_set "$key" "$value"
            if [ "$sub" = unset ]; then echo "$key unset: the default applies."
            elif is_secret_key "$key"; then echo "$key set (hidden)."
            else echo "$key=$value"; fi
            if [ "$apply" = 1 ]; then config_apply "$key"; else echo "Not applied (--no-apply): 'smoking-pi up' picks it up."; fi
            ;;
        -h|--help) usage ;;
        *) echo "unknown config command: $sub (list, get, set, unset)" >&2; return 2 ;;
    esac
}
