apiVersion: 1
envInterpolation: true          # ← move it here (2 spaces in)

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false

    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      httpMode: POST

    secureJsonData:
      token: ${INFLUX_TOKEN}